"""empty message

Revision ID: 7e52b531ff6b
Revises: f012461853cb
Create Date: 2021-04-14 00:20:54.772139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e52b531ff6b'
down_revision = 'f012461853cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'create_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('create_time', sa.VARCHAR(length=65), nullable=True))
    # ### end Alembic commands ###
