"""the second migration

Revision ID: c0d04bfbef48
Revises: f667bfb1b05b
Create Date: 2021-04-13 21:03:00.906967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d04bfbef48'
down_revision = 'f667bfb1b05b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('create_date', sa.String(length=65), nullable=True))
    op.drop_column('articles', 'create_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('create_time', sa.VARCHAR(length=65), nullable=True))
    op.drop_column('articles', 'create_date')
    # ### end Alembic commands ###
