"""the second migration

Revision ID: f667bfb1b05b
Revises: 0faa4fa98e22
Create Date: 2021-04-13 21:00:55.402934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f667bfb1b05b'
down_revision = '0faa4fa98e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('create_time', sa.String(length=65), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'create_time')
    # ### end Alembic commands ###
